name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Docker image
      run: |
        docker build \
        -t ${{ secrets.DOCKER_USER }}/dzlinux:build-${{ github.sha }} \
        -t ${{ secrets.DOCKER_USER }}/dzlinux:latest \
        -f docker/Dockerfile \
        docker/

        echo "Docker image built successfully"
        docker images | grep ${{ secrets.DOCKER_USER }}/dzlinux

  test:
    runs-on: ubuntu-latest
    needs: verify
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s

    steps:
      - uses: actions/checkout@v4
      - name: Build app image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USER }}/dzlinux:build-${{ github.sha }} \
          -t ${{ secrets.DOCKER_USER }}/dzlinux:latest \
          -f docker/Dockerfile \
          docker/

          echo "Docker image built successfully"
          docker images | grep ${{ secrets.DOCKER_USER }}/dzlinux

      - name: Run tests
        run: |
          docker run --network host \
            -e TEST=1 \
            ${{ secrets.DOCKER_USER }}/dzlinux:build-${{ github.sha }} pytest -v ./tests/

      - name: Push to docker registry
        if: success()
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker push kalininasofa/dzlinux:build-${{ github.sha }}
          docker push kalininasofa/dzlinux:latest
          echo "Would have pushed app:${{ github.sha }}"
          
  deploy:
    runs-on: self-hosted
    needs: [ test ]
    steps:
      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: cd $HOME/tasks/docker && ./restart.sh
